---
title: "Resultados"
author: "Michael Velandia"
date: "17/05/2021"
output: 
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source("Code/eda.R")
```

## Resultados 

Los resultados 

```{r summary, echo=FALSE,  message=FALSE, warning=FALSE, fig.height= 6, fig.width= 9, fig.align='center' }

summary_data <- (function () {
    summary_data <- summary_statistics()
    mean <-  summary_data$mean %>% 
             column_to_rownames("Estacion") %>%
             round(digits = 2)
    sd <-  summary_data$sd %>% 
             column_to_rownames("Estacion") %>%
             round(digits = 2)
    data <- list(Estacion = summary_data$mean[["Estacion"]])
    
    for (i in 1:8){
        a <- paste0( mean[[i]], '±', sd[[i]]) 
        data[[1+i]] <- a
    }
    
    data <- as.data.frame(data)
    names(data) <-  names(summary_data$mean)
    data <- left_join(data, summary_data$macroinvertebrates, by = "Estacion")
    names(data) <- gsub("_", " ", names(data))
    
    return(data)
})()

doc.type <- knitr::opts_knit$get('rmarkdown.pandoc.to')

if (doc.type == "docx") {
    
  summary_data %>%
      flextable() %>%
      set_caption( caption = "New York Air Quality Measurements") %>% ## Change caption and footer
      add_footer_lines(values = "Daily air quality measurements in New Y")

} else {
    
  summary_data %>%
      kbl(booktabs = TRUE, escape = FALSE, caption = " Categorias de los Rasgos Funcionales")

}
```

```{r eda,  message=FALSE, warning=FALSE, cache= FALSE, echo=FALSE, fig.height= 6, fig.width= 9, fig.align='center'}
plot_pca <- make_pca( plot_type = "Tipo_Estacion")
plot_cluster <-  make_cluster()
layout <- "
AAAAAAACCCC
AAAAAAABBBB
AAAAAAABBBB
AAAAAAABBBB
"
plot_pca$biplot + 
  plot_cluster$dendogram + 
  plot_pca$eigenvalues + 
  plot_layout(design = layout, guides = 'collect') +
  guide_area() +
  plot_annotation(tag_levels = 'A') 
  

```

```{r rlq ,  message=FALSE, warning=FALSE, cache= FALSE, echo=FALSE, fig.height= 11, fig.width= 10}
rlq1 <- make_rlq()
data <- load_rlq()$R_table
estations <- cbind( Grupo =factor(data$Tipo_Estacion),rlq1$mR) 
mean_estations <- estations %>% 
                 group_by(Grupo) %>%
                summarise(across(.cols = everything() , mean))

custom_palette <- c("#FF6F00FF", "#C71000FF", "#008EA0FF", "#8A4198FF")
rasgos <-  c("Tipo Alimento", 
            "Habitos Alimenticios", 
            "Respiracion",
            "Forma Corporal", 
            "Movilidad",
            "Tamaño Maximo")

{
    par(mfrow= c(3,2))

    {
        plot(1, type="n", xlab="", ylab="", 
             ylim = c(-3,3), xlim = c(-3,3), axes = FALSE);
        palette(custom_palette)
        points(estations[[2]], estations[[3]],
               col = estations$Grupo, pch = 18);
        text(mean_estations[[2]], mean_estations[[3]],
               labels =  mean_estations$Grupo,
               col = custom_palette)
        par(new= TRUE);
        palette(gray(0:1));
        s.label(rlq1$co[1:7,], boxes = FALSE,  clabel = 2,
                ylim = c(-1,1), xlim = c(-1.5,1.5),
                sub = rasgos[1], csub = 2.5);
        s.arrow(rlq1$l1, boxes = TRUE, add.plot = TRUE, clabel = 2);
      
    }
  
    {
        plot(1, type="n", xlab="", ylab="", 
             ylim = c(-3,3), xlim = c(-3,3), axes = FALSE);
        palette(custom_palette)
        points(estations[[2]], estations[[3]],
               col = estations$Grupo, pch = 18);
        text(mean_estations[[2]], mean_estations[[3]],
               labels =  mean_estations$Grupo,
               col = custom_palette)
        par(new= TRUE);
        palette(gray(0:1));
        s.label(rlq1$co[8:14,], boxes = FALSE,  clabel = 2,
                ylim = c(-1,1), xlim = c(-1.5,1.5),
                sub = rasgos[2], csub = 2.5);
        s.arrow(rlq1$l1, boxes = TRUE, add.plot = TRUE, clabel = 2);
      
    }
  
    {
        plot(1, type="n", xlab="", ylab="", 
             ylim = c(-3,3), xlim = c(-3,3), axes = FALSE);
        palette(custom_palette)
        points(estations[[2]], estations[[3]],
               col = estations$Grupo, pch = 18);
        text(mean_estations[[2]], mean_estations[[3]],
               labels =  mean_estations$Grupo,
               col = custom_palette)
        par(new= TRUE);
        palette(gray(0:1));
        s.label(rlq1$co[15:19,], boxes = FALSE,  clabel = 2,
                ylim = c(-1,1), xlim = c(-1.5,1.5),
                sub = rasgos[3], csub = 2.5);
        s.arrow(rlq1$l1, boxes = TRUE, add.plot = TRUE, clabel = 2);
      
    }
    
    {
        plot(1, type="n", xlab="", ylab="", 
             ylim = c(-3,3), xlim = c(-3,3), axes = FALSE);
        palette(custom_palette)
        points(estations[[2]], estations[[3]],
               col = estations$Grupo, pch = 18);
        text(mean_estations[[2]], mean_estations[[3]],
               labels =  mean_estations$Grupo,
               col = custom_palette)
        par(new= TRUE);
        palette(gray(0:1));
        s.label(rlq1$co[20:23,], boxes = FALSE,  clabel = 2,
                ylim = c(-1,1), xlim = c(-1.5,1.5),
                sub = rasgos[4], csub = 2.5);
        s.arrow(rlq1$l1, boxes = TRUE, add.plot = TRUE, clabel = 2);
      
    }
    
    {
        plot(1, type="n", xlab="", ylab="", 
             ylim = c(-3,3), xlim = c(-3,3), axes = FALSE);
        palette(custom_palette)
        points(estations[[2]], estations[[3]],
               col = estations$Grupo, pch = 18);
        text(mean_estations[[2]], mean_estations[[3]],
               labels =  mean_estations$Grupo,
               col = custom_palette)
        par(new= TRUE);
        palette(gray(0:1));
        s.label(rlq1$co[24:29,], boxes = FALSE,  clabel = 2,
                ylim = c(-1,1), xlim = c(-1.5,1.5),
                sub = rasgos[5], csub = 2.5);
        s.arrow(rlq1$l1, boxes = TRUE, add.plot = TRUE, clabel = 2);
      
    }
    
    {
        plot(1, type="n", xlab="", ylab="", 
             ylim = c(-3,3), xlim = c(-3,3), axes = FALSE);
        palette(custom_palette)
        points(estations[[2]], estations[[3]],
               col = estations$Grupo, pch = 18);
        text(mean_estations[[2]], mean_estations[[3]],
               labels =  mean_estations$Grupo,
               col = custom_palette)
        par(new= TRUE);
        palette(gray(0:1));
        s.label(rlq1$co[30:34,], boxes = FALSE,  clabel = 2,
                ylim = c(-1,1), xlim = c(-1.5,1.5),
                sub = rasgos[6], csub = 2.5);
        s.arrow(rlq1$l1, boxes = TRUE, add.plot = TRUE, clabel = 2);
    }
}
  

```

```{r , fig.height= 3, fig.width= 10}
{
   par(mfrow = c(1,3)) 
   s.corcircle(rlq1$aR, sub = "enviromental axes", csub = 2, clabel = 1.25)
   barplot((rlq1$eig/sum(rlq1$eig)), names.arg = 1:5, 
          ylab = '% Varianza explicada', xlab = 'Dimensión', ylim = c(0,1))
   s.corcircle(rlq1$aQ, sub = "traits axes", csub = 2, clabel = 1.25) 
}
```

```{r fourthcorner}
fourth_corner <- make_rlq(fourthcorner = TRUE)


```

```{r CA }

# REFACTORIZE NOT WORK ANYMORE
# rlq1 <- make_rlq()
# 
# eig_CA <- round(abundance_test$eig / sum(abundance_test$eig) * 100,2)
# table_ca <- data_frame(Dimensiones = 1:10, '% Varianza' = eig_CA[1:10])
# 
# ca_table <- tableGrob(table_ca, rows = NULL)
# ca_plot <- fviz_ca(abundance_test, col.row = data$L_table[["Tipo_Estacion"]], geom.row = "point")
# 
# ca_plot + ca_table
```

## Anexos 

### Analisis univarido

En las figuras ?-1 al ?-10 se observan los diagramas de caja y los graficos
cuantil-cuantil que corresponden a un analisis exploratorio de las variables 
fisicoquimicas.   
```{r anexos_eda, message=FALSE, warning=FALSE, cache=FALSE,include = TRUE, echo = FALSE, fig.height= 9, fig.width= 6, fig.align='center'}
qq_plots <- univariate_graphical_eda(type_plot = 'quantile-normal')
box_plots <-  univariate_graphical_eda(type_plot = 'boxplot')


  qq_plots$Ox_disuelto + 
  qq_plots$Turbidez +
  qq_plots$pH +
  box_plots$Ox_disuelto + 
  box_plots$Turbidez +
  box_plots$pH +
  plot_layout(ncol = 2, byrow = FALSE ) 
  
```

```{r anexos_eda2 , message=FALSE, warning=FALSE, cache=TRUE ,include = TRUE, echo = FALSE, fig.height= 6, fig.width= 6, fig.align='center'}
qq_plots <- univariate_graphical_eda(type_plot = 'quantile-normal')
box_plots <-  univariate_graphical_eda(type_plot = 'boxplot')

qq_plots$Conductividad + 
  qq_plots$Temperatura +
    box_plots$Conductividad + 
  box_plots$Temperatura +
  plot_layout(ncol = 2, byrow = FALSE )

```

```{r anexos_eda3 , message=FALSE, warning=FALSE, cache=TRUE ,include = TRUE, echo = FALSE, fig.height= 6, fig.width= 6, fig.align='center'}
qq_plots <- univariate_graphical_eda(type_plot = 'quantile-normal')
box_plots <-  univariate_graphical_eda(type_plot = 'boxplot')

qq_plots$Area + 
  qq_plots$Profundidad +
  qq_plots$Velocidad + 
  box_plots$Area +
  box_plots$Profundidad + 
  box_plots$Velocidad +
  plot_layout(ncol = 2, byrow = FALSE )

```

```{r,  message=FALSE, warning=FALSE,}
results_manova <- list(
NeuA_NeuB  = make_manova(est1 = "NeusaA", est2 = "NeusaB"),
NeuA_FrioA =  make_manova(est1 = "NeusaA", est2 = "FrioA"),
NeuA_FrioB =  make_manova(est1 = "NeusaA", est2 = "FrioB"),
NeuB_FrioA =  make_manova(est1 = "NeusaB", est2 = "FrioA"),
NeuB_FrioB =  make_manova(est1 = "NeusaB", est2 = "FrioB"),
FrioA_FrioB =  make_manova(est1 = "FrioA", est2 = "FrioB")
)

 for (i in 1:6) { 
     print(names(results_manova[i]))
     print(results_manova[[i]])
     print("\n")
 }

```

```{r}
plot_pca <- make_pca(parameters = c('Area', 'Profundidad', 'Velocidad' ), plot_type = "Tipo_Estacion")
plot_pca

```

